### ISSUE TITLE
notifications are going into Spam in GMail

### ISSUE THREAD

**Issue by rgommers** [openteamsinc/websitefeedback#12]
Happened to discover this just now. I received two notifications on Aug 24th, sender is `noreply@openteams.com`, and subjects `Contribution claim has been submitted.`, `Contribution claim has been endorsed.`

**Comment by dcharbon** [comment]
We're hoping to have a fix for this going in Friday, September 6.

**Comment by dcharbon** [comment]
We've adopted a new transactional email provider. From the dashboard we are doing much much better here, very few bounced or spam-foldered messages.
