### ISSUE TITLE
Contribution claims aren't readable

### ISSUE THREAD

**Issue by rgommers** [openteamsinc/websitefeedback#14]
When attempting to approve a contribution claim that's pending, there is no way to read full text of what the contributor actually claimed. The text begins (screenshot below) _Principal maintainer of PyData/Sparse, a..._ but that can't be expanded (a click on the text gets me to the users profile, not to the claim.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/98330/65127819-8fd92400-d9f8-11e9-8d79-cba227df82e3.png">

**Comment by rgommers** [comment]
It's worse actually, that cut-off text is the profile text not the claim. The claim is completely invisible. One more screenshot, for a new contribution claim from someone without a profile: 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/98330/65148858-451fd200-da21-11e9-91b8-6c84b073142c.png">

**Comment by rgommers** [comment]
Something got fixed:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/98330/65372843-7ee91680-dc75-11e9-8401-3ac0d801ea97.png">

It's still not possible to read the whole text, it's cut off after ~76 characters, so I won't close this. But it helps.

**Comment by dcharbon** [comment]
This has been fixed.
