### ISSUE TITLE
"Thank a contributor" is broken

### ISSUE THREAD

**Issue by rgommers** [openteamsinc/websitefeedback#15]
Clicking on "Thank a contributor" on the NumPy project shows a project name dropdown that can't be used, and adding an email address is not accepted.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/98330/65373163-2405ee00-dc7a-11e9-8cab-abe5df2651b0.png">

**Comment by dcharbon** [comment]
Sorry for the late response - this was fixed.
